TABELA DESNORMALIZADA PARA RELATÓRIOS

CREATE TABLE RELATORIO_PRODUCAO(
    ID_LOTE NUMBER(10)NOT NULL,
    DATA_PRODUCAO DATE NOT NULL,
    QUANTIDADE_TONELADAS NUMBER (10,2)NOT NULL,
    STATUS VARCHAR2(20)NOT NULL,
    TIPO_CONCRETO VARCHAR2(100)NOT NULL,
    NOME_CLIENTE VARCHAR2(100)NOT NULL,
    NOME_FUNCIONARIO VARCHAR2(100)NOT NULL,
    PLACA_VEICULO VARCHAR2(13)NOT NULL
);

INSERT INTO RELATORIO_PRODUCAO(
    ID_LOTE,
    DATA_PRODUCAO,
    QUANTIDADE_TONELADAS,
    STATUS,
    TIPO_CONCRETO,
    NOME_CLIENTE,
    NOME_FUNCIONARIO,
    PLACA_VEICULO
)

SELECT
LP.ID_LOTE,
LP.DATA_PRODUCAO,
LP.QUANTIDADE_TONELADAS,
LP.STATUS,
RT.TIPO_CONCRETO,
C.NOME_CLIENTE,
F.NOME_FUNCIONARIO,
V.PLACA_VEICULO 
FROM LOTES_DE_PRODUCAO LP 
JOIN RECEITA_TECNICA RT ON LP.ID_RECEITA = RT.ID_RECEITA
JOIN CLIENTE C ON LP.ID_CLIENTE = C.ID_CLIENTE
JOIN FUNCIONARIO F ON LP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
JOIN VEICULO V ON LP.ID_VEICULO = V.ID_VEICULO